version: '3'

services:
  db:
    container_name: techin-postgres
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:14.4
    restart: unless-stopped

  pgadmin:
    container_name: techin-pgadmin
    ports:
      - 4433:443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
    image: dpage/pgadmin4:latest
    restart: unless-stopped
  
  strapi:
    container_name: techin-myapp
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=${D_CLIENT}
      - DATABASE_HOST=${D_HOST}
      - DATABASE_PORT=${D_PORT}
      - DATABASE_NAME=${D_NAME}
      - DATABASE_USERNAME=${D_USERNAME}
      - DATABASE_PASSWORD=${D_PASSWORD}
      - DATABASE_SSL=${D_SSL}
    image: naskio/strapi:latest
    restart: unless-stopped
